### Signup
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "kloof_open1@dev.com",
    "password": "12345678"
}

### Signin
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email": "kloof_109@dev.com",
    "password": "12345666"
}

### User test auth guard
GET http://localhost:3000/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiZW1haWwiOiJrbG9vZl8xMDlAZGV2LmNvbSIsImlhdCI6MTY3ODcwMjUyMCwiZXhwIjoxNjc4NzAzNDIwfQ.DnXi28YYcPym8nULCyNZfX41hb99XqfWh7hf_WnJ5YQ

### Test 
GET http://localhost:3000/auth/test